# ============================
# Gradle / JVM
# ============================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# ============================
# Kotlin
# ============================
kotlin.code.style=official

# ============================
# Android
# ============================
android.useAndroidX=true
android.nonTransitiveRClass=true

# ✅ Suprime el warning de AGP 8.2.2 con compileSdk = 36
android.suppressUnsupportedCompileSdk=36
